export default [
  {
    path: '/user',
    layout: false,
    routes: [
      { name: '登录', path: '/user/login', component: './user/Login' },
      { name: '忘记密码', path: '/user/restore', component: './user/Restore' },
      { component: './404' },
    ],
  },
  { path: '/init', layout: false, component: './InitPage' },
  {
    path: '/welcome',
    name: '分析概览',
    icon: 'smile',
    component: './Welcome',
    access: 'isAdmin',
  },
  { name: '文章管理', icon: 'form', path: '/article', component: './Article' },
  {
    name: '图形编辑器',
    icon: 'form',
    path: '/editor',
    component: './Editor',
    hideInMenu: true,
  },
  {
    name: '代码编辑器',
    icon: 'tool',
    path: '/code',
    component: './Code',
    hideInMenu: true,
    access: 'isAdmin',
  },
  {
    name: '关于',
    icon: 'form',
    path: '/about',
    component: './About',
    hideInMenu: true,
  },
  { name: '草稿管理', icon: 'container', path: '/draft', component: './Draft' },
  {
    name: '图片管理',
    icon: 'picture',
    path: '/static/img',
    hideInBreadcrumb: true,
    component: './Static/img',
  },
  {
    name: '数据管理',
    icon: 'table',
    path: '/site/data',
    component: './DataManage',
    hideInBreadcrumb: true,
    access: 'isAdmin',
  },
  {
    name: '评论管理',
    icon: 'comment',
    path: '/site/comment',
    // component: './CommentManage',
    hideInBreadcrumb: true,
    access: 'isAdmin',
  },
  {
    name: '流水线',
    icon: 'cluster',
    path: '/site/pipeline',
    component: './Pipeline',
    hideInBreadcrumb: true,
    access: 'isAdmin',
  },
  {
    name: '系统设置',
    icon: 'setting',
    path: '/site/setting',
    component: './SystemConfig',
    hideInBreadcrumb: true,
    access: 'isAdmin',
  },
  {
    name: '自定义页面',
    icon: 'profile',
    path: '/site/customPage',
    component: './CustomPage',
    hideInBreadcrumb: true,
    access: 'isAdmin',
  },
  {
    name: '日志管理',
    icon: 'file-text',
    path: '/site/log',
    component: './LogManage',
    hideInBreadcrumb: true,
    access: 'isAdmin',
  },
  { path: '/', redirect: '/article' },
  { component: './404' },
];
